title: Ignacio Estrada
description: Software Engineer | HCI & APP Debelopment | Open Source Contributor

theme: minima

# Menu
header_pages:
  - about.md
  - projects.md

#Socials
github_username: ire2
linkedin: https://www.linkedin.com/in/ignacio-ec